// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTusCzu7xcUCaaGNzu_P5HW7ibN0tyPHw',
    appId: '1:491221466430:web:2912e111deeb4ef28ec06f',
    messagingSenderId: '491221466430',
    projectId: 'guasa-hbardc',
    authDomain: 'guasa-hbardc.firebaseapp.com',
    storageBucket: 'guasa-hbardc.firebasestorage.app',
    measurementId: 'G-D64MY7799C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLGxlrA7T6-XZhFfKoTDfxJlKOm0XPGu4',
    appId: '1:491221466430:android:e4e5ccd7d5a363b28ec06f',
    messagingSenderId: '491221466430',
    projectId: 'guasa-hbardc',
    storageBucket: 'guasa-hbardc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6QL-t5QNkbzS2m9h-EKytvLnj8Y3Wuo',
    appId: '1:491221466430:ios:44638208acadf20b8ec06f',
    messagingSenderId: '491221466430',
    projectId: 'guasa-hbardc',
    storageBucket: 'guasa-hbardc.firebasestorage.app',
    iosBundleId: 'com.example.guasas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTusCzu7xcUCaaGNzu_P5HW7ibN0tyPHw',
    appId: '1:491221466430:web:ed531e4d109292758ec06f',
    messagingSenderId: '491221466430',
    projectId: 'guasa-hbardc',
    authDomain: 'guasa-hbardc.firebaseapp.com',
    storageBucket: 'guasa-hbardc.firebasestorage.app',
    measurementId: 'G-V0HKMBF1SV',
  );
}
